spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # QueryDSL 실제로 execute된 JPQL을 볼 수 있음

#  profiles:
#    active: dev # dev 프로필을 사용중일 때는 더미데이터 추가

jwt:
  secret: ${JWT_SECRET_KEY} # openssl rand -hex 32
  access-token-expiration: 1800 # 30분
  refresh-token-expiration: 2592000 # 30일

logging:
  level:
    org.hibernate.SQL: debug

file:
  upload-dir: ./uploads/

app:
  web-application-server-url: ${DOMAIN_URL}
  web-server-url: ${DOMAIN_URL}

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
  cloud-front:
    url: ${CLOUD_FRONT_URL}