spring:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/mika_community?serverTimezone=UTC&useSSL=false
    username: ${MY_SQL_USERNAME}
    password: ${MY_SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # QueryDSL 실제로 execute된 JPQL을 볼 수 있음

  profiles:
    active: dev # dev 프로필을 사용중일 때는 더미데이터 추가

jwt:
  secret: f175da761cb740d03f9e43ac4d78a438e051bb73a7163624a10d97e4f015c6f9 # openssl rand -hex 32
  access-token-expiration-ms: 1800000 # 30분
  refresh-token-expiration-ms: 604800000 # 7일

logging:
  level:
    org.hibernate.SQL: debug